# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e07ca7ac801dc3a68f60a20936779bafea4a3c9c7c8c923c926e01b12c28548bb653d7ac6703b8659a0f21aeab51f024c155778989a1a8780176870ed9869bf8

test:
  secret_key_base: 6e43c87387d7ffe9fb5363d3e0f620df298e91169c385b8315bc1226b5b96fcd7b7e15c6a599bf56e9b3ee714a0a73d3336bf4ba13f1b19aa4590d4027ebb9e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
